# This is a basic workflow to help you get started with Actions
name: Update Github Stats

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "47 2 * * *"  # Fixed: was missing the day of week field
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]  # Updated to Node.js 18 (Node 14 is EOL)
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4  # Updated from v2 to v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # Updated from v2 to v4
        with: 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          # Add cache-dependency-path if your package.json is not in root
          # cache-dependency-path: './package.json'
      
      # Install requirements
      - name: Install requirements
        run: npm ci  # Use npm ci instead of npm install for CI environments
          
      - name: Github Configurations
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "action@github.com"
          
      - name: Update Template
        run: |
          node updater.js ${{ github.repository_owner }} atom
        env:
          GHT: ${{ secrets.GHT }}
          
      # Committing
      - name: Commit changed svg template
        run: |
          git add .
          git diff --staged --quiet || git commit -m "Github Stats updated 🎉"
          git push
